### ISSUE TITLE
My title bar looks a bit different from the one you show in the preview.

### ISSUE THREAD

**Issue by seriaati** [bentettmar/bubblecord#1]
This is mine:
![image](https://user-images.githubusercontent.com/61446626/138798171-9e4e73ab-ae58-44d8-b179-347d1fab72c0.png)

As you can see there is only the red circle but the yellow and green are missing.
I am using windows 11, I don't know if that affects it.

**Comment by bentettmar** [comment]
that shouldnt effect it, not sure why its doing that
