### ISSUE TITLE
1 box still missing.

### ISSUE THREAD

**Issue by mcspidey95** [bentettmar/bubblecord#3]
![Screenshot_81](https://user-images.githubusercontent.com/90018162/154193353-c8d1b1e2-bb8d-4e6c-a637-49aeb41e9dd0.png)
![Screenshot_82](https://user-images.githubusercontent.com/90018162/154193358-c540f082-9f35-481b-ac7f-75c86d2a885c.png)

you can see on the preview there's a bubble/box layout for the members section as well, which you don't see on my screenshot.. the other bubbles/ boxes are there, after updating like you said. just that bubble layout left.. Try fixing that if you can. I'm fine with it either ways, just prefer the box. thenks btw :)

**Comment by mcspidey95** [comment]
![Screenshot_83](https://user-images.githubusercontent.com/90018162/154193694-dfd33a90-53fe-4f20-b255-6819b13e3d56.png)

i also just found this.. 

(like i said, do it when you can. Don't wanna trouble you)

**Comment by bentettmar** [comment]
Yes, when i was updating to the new class names i forgot to do that, i will update this asap.

**Comment by bentettmar** [comment]
the space on the settings scroller cant be removed.

**Comment by mcspidey95** [comment]
yeah, thats fine. dont really care abt that.

**Comment by bentettmar** [comment]
Okay, everything has been fixed and updated, download it again or update it in powercord :).
